export const BRANDS_FETCH_START = 'BRANDS_FETCH_START';
export const BRANDS_FETCH_SUCCESS = 'BRANDS_FETCH_SUCCESS';
export const BRANDS_FETCH_FAILURE = 'BRANDS_FETCH_FAILURE';
export const PRODUCTS_FETCH_START = 'PRODUCTS_FETCH_START';
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS';
export const PRODUCTS_FETCH_FAILURE = 'PRODUCTS_FETCH_FAILURE';
